/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket.Frame;

import java.text.ParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import supermarket.Controller.MainController;
import supermarket.Helper.Helper;

/**
 *
 * @author Iqbal
 */
public class Storage extends javax.swing.JFrame {
    private final MainController controller;
    private String product_id;
    
    /**
     * Creates new form Storage
     */
    public Storage() {
        initComponents();
        MainController mainController = new MainController();
        controller = mainController;
        
        loadTableProduct();
        loadTableSold();
        clearForm();
        clearForm1();
    }
    
    private void loadTableProduct(){
        String sql = "SELECT ID, Name, Type, Supplier, Amount, Price, Expired,"
                + " Purchase_Date from product WHERE status = 1";
        controller.get(tb_stock, sql);
        controller.get(tb_stock1, sql);
        System.out.println("Worked!");
    }
    
    private void loadTableSold(){
        String sql = "SELECT Product_ID, Sell_ID, Sell_Price, Sell_Amount, "
                + "Sell_Date, Total_Price from sold_items "
                + "WHERE status = 1";
        controller.get(tb_soldItems, sql);
        System.out.println("Worked!!");
    }
    
    private void clearForm(){
        tf_name.setText(null);
        cb_type.setSelectedIndex(0);
        cb_supplier.setSelectedIndex(0);
        tf_amount.setText(null);
        tf_price.setText(null);
        dp_expired.setDate(null);
        dp_purchaseDate.setDate(null);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_submit.setEnabled(true);
    }
    
    private void clearForm1(){
        tf_sellPrice.setText(null);
        tf_purchaseAmount.setText(null);
        dp_purchaseDate1.setDate(null);
        lbl_totalPrice.setText(null);
        btn_delete1.setEnabled(false);
        btn_submit1.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        dp_expired = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_price = new javax.swing.JTextField();
        cb_supplier = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cb_type = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_stock = new javax.swing.JTable();
        tf_search = new javax.swing.JTextField();
        btn_searchID = new javax.swing.JButton();
        btn_searchName = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        dp_purchaseDate = new org.jdesktop.swingx.JXDatePicker();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        tf_sellPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_purchaseAmount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dp_purchaseDate1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel19 = new javax.swing.JLabel();
        lbl_totalPrice = new javax.swing.JLabel();
        btn_submit1 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_stock1 = new javax.swing.JTable();
        tf_search1 = new javax.swing.JTextField();
        btn_searchID1 = new javax.swing.JButton();
        btn_searchName1 = new javax.swing.JButton();
        btn_refresh1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tb_soldItems = new javax.swing.JTable();
        tf_search2 = new javax.swing.JTextField();
        btn_searchID2 = new javax.swing.JButton();
        btn_refresh2 = new javax.swing.JButton();
        btn_delete1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Storage");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Expired");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Product Name");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Amount");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Supplier");

        cb_supplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IndoFood Company", "Nestule Corp", "Ace Hardware", "Sanitary & Hygiene Emterprise", "Unicharm Corp" }));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Product Type");

        cb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Beverage", "Household Item" }));
        cb_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_typeMouseClicked(evt);
            }
        });
        cb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_typeActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Retail Price");

        tb_stock.setBackground(new java.awt.Color(204, 204, 255));
        tb_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_stockMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_stock);

        btn_searchID.setText("Search by ID");
        btn_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIDjButton1ActionPerformed(evt);
            }
        });

        btn_searchName.setText("Search by Name");
        btn_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchNamejButton2ActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh Table");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 334, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchID)
                    .addComponent(btn_searchName)
                    .addComponent(btn_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatejButton1ActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitjButton1ActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletejButton1ActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Purchase Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_name)
                            .addComponent(tf_amount)
                            .addComponent(cb_supplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_price)
                            .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dp_expired, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dp_purchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dp_purchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dp_expired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventory", jPanel5);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("ID");

        lbl_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Retail Sell Price");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Purchase Amount");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Purchase Date");

        dp_purchaseDate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dp_purchaseDate1MouseClicked(evt);
            }
        });
        dp_purchaseDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_purchaseDate1ActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Total Price");

        lbl_totalPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_submit1.setText("Submit");
        btn_submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit1jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane3MouseClicked(evt);
            }
        });

        tb_stock1.setBackground(new java.awt.Color(204, 204, 255));
        tb_stock1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_stock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_stock1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tb_stock1);

        btn_searchID1.setText("Search by ID");
        btn_searchID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchID1jButton1ActionPerformed(evt);
            }
        });

        btn_searchName1.setText("Search by Name");
        btn_searchName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchName1jButton2ActionPerformed(evt);
            }
        });

        btn_refresh1.setText("Refresh Table");
        btn_refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh1jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane7)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_searchID1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_searchName1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchID1)
                    .addComponent(btn_searchName1)
                    .addComponent(btn_refresh1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Table Stock", jPanel2);

        tb_soldItems.setBackground(new java.awt.Color(204, 204, 255));
        tb_soldItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_soldItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_soldItemsMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tb_soldItems);

        btn_searchID2.setText("Search by ID");
        btn_searchID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchID2jButton1ActionPerformed(evt);
            }
        });

        btn_refresh2.setText("Refresh Table");
        btn_refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh2jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_searchID2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchID2)
                    .addComponent(btn_refresh2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Table Sold Items", jPanel4);

        btn_delete1.setText("Delete");
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_sellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_purchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dp_purchaseDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_purchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dp_purchaseDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Stock", jPanel9);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Sell Items", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(655, 655, 655)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(998, 998, 998))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        loadTableProduct();
        loadTableSold();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btn_deletejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletejButton1ActionPerformed
        try{
            // TODO add your handling code here:

            String sql = "UPDATE product SET status = 0 WHERE ID = ?";

            Map<Integer, Object> map = new HashMap<>();
            map.put(1, this.product_id);

            if(controller.preparedStatement(map, sql)){
                clearForm();
                loadTableProduct();
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
                btn_submit.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_deletejButton1ActionPerformed

    private void btn_submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitjButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String name = tf_name.getText();
            String type = cb_type.getSelectedItem().toString();
            String supplier = cb_supplier.getSelectedItem().toString();
            String amount = tf_amount.getText();
            String price = tf_price.getText();

            Helper helper = new Helper();
            String purchaseDate = helper.parseDateToDatabase(dp_purchaseDate);

            
            if(cb_type.getSelectedItem() == "Household Item"){
                String sql = "INSERT INTO product (Name, Type, Supplier, "
            + " Amount, Price, Purchase_Date, Expired, Status) "
            + "values (?,?,?,?,?,?,null,1)";
            
                Map<Integer, Object> map = new HashMap<>();
            map.put(1, name);
            map.put(2, type);
            map.put(3, supplier);
            map.put(4, amount);
            map.put(5, price);
            map.put(6, purchaseDate);
            

            if(!controller.preparedStatement(map, sql)){
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan Data");
            }
            else{
                clearForm();
                loadTableProduct();
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
            }
            }else{
            String expired = helper.parseDateToDatabase(dp_expired);
            
                String sql = "INSERT INTO product (Name, Type, Supplier, "
            + " Amount, Price, Expired, Purchase_Date, Status) "
            + "values (?,?,?,?,?,?,?,1)";
            
                Map<Integer, Object> map = new HashMap<>();
            map.put(1, name);
            map.put(2, type);
            map.put(3, supplier);
            map.put(4, amount);
            map.put(5, price);
            map.put(6, expired);
            map.put(7, purchaseDate);

            if(!controller.preparedStatement(map, sql)){
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan Data");
            }
            else{
                clearForm();
                loadTableProduct();
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
            }
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_submitjButton1ActionPerformed

    private void btn_updatejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatejButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String name = tf_name.getText();
            String type = cb_type.getSelectedItem().toString();
            String supplier = cb_supplier.getSelectedItem().toString();
            String amount = tf_amount.getText();
            String price = tf_price.getText();

            Helper helper = new Helper();
            String expired = helper.parseDateToDatabase(dp_expired);
            String purchaseDate = helper.parseDateToDatabase(dp_purchaseDate);

            String sql = "UPDATE product SET Name = ?, Type = ?, Supplier = ?, "
            + " Amount = ?, Price = ?, Expired = ?, Purchase_Date = ? "
            + "WHERE ID = ?";

            Map<Integer, Object> map = new HashMap<>();
            map.put(1, name);
            map.put(2, type);
            map.put(3, supplier);
            map.put(4, amount);
            map.put(5, price);
            map.put(6, expired);
            map.put(7, purchaseDate);
            map.put(8, this.product_id);

            if(controller.preparedStatement(map, sql)){
                clearForm();
                loadTableProduct();
                JOptionPane.showMessageDialog(null, "Berhasil Merubah Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Merubah Data");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_updatejButton1ActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        loadTableProduct();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_searchNamejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchNamejButton2ActionPerformed
        // TODO add your handling code here:
        String search = tf_search.getText();
        String sql = "SELECT ID, Name, Type, Supplier, Amount, Price, Expired,"
                + " Purchase_Date FROM product WHERE Name LIKE '"+ search +"%' AND status != 0;";
        controller.get(tb_stock, sql);
    }//GEN-LAST:event_btn_searchNamejButton2ActionPerformed

    private void btn_searchIDjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIDjButton1ActionPerformed
        // TODO add your handling code here:
        String search = tf_search.getText();
        String sql = "SELECT ID, Name, Type, Supplier, Amount, Price, Expired,"
                + " Purchase_Date FROM product WHERE ID = ? AND status != 0";
        Map<Integer, Object> map = new HashMap<>();
        map.put(1, search);

        controller.getWithParameter(tb_stock, map, sql);
    }//GEN-LAST:event_btn_searchIDjButton1ActionPerformed

    private void tb_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_stockMouseClicked
        try {
            // TODO add your handling code here:
            Helper helper = new Helper();
            String id = helper.getValueRows(tb_stock, 0);
            String name = helper.getValueRows(tb_stock, 1);
            String type = helper.getValueRows(tb_stock, 2);
            String supplier = helper.getValueRows(tb_stock, 3);
            String amount = helper.getValueRows(tb_stock, 4);
            String price = helper.getValueRows(tb_stock, 5);
            String expired = helper.getValueRows(tb_stock, 6);
            String purchaseDate = helper.getValueRows(tb_stock, 7);

            btn_update.setEnabled(true);
            btn_delete.setEnabled(true);
            btn_submit.setEnabled(false);

            this.product_id = id;
            tf_name.setText(name);
            cb_type.setSelectedItem(type);
            cb_supplier.setSelectedItem(supplier);
            tf_amount.setText(amount);
            tf_price.setText(price);
            dp_expired.setDate(new Date(helper.getParsedDate(expired)));
            dp_purchaseDate.setDate(new Date(helper.getParsedDate(purchaseDate)));
        } catch (ParseException ex) {
            Logger.getLogger(Storage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_stockMouseClicked

    private void option(){
        if(cb_type.getSelectedItem() == "Household Item"){
            dp_expired.setEnabled(false);
            dp_expired.setDate(null);
        }
        else{
            dp_expired.setEnabled(true);
        }
    }
    
    private void cb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_typeActionPerformed
        // TODO add your handling code here:
        option();
    }//GEN-LAST:event_cb_typeActionPerformed

    private void tb_stock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_stock1MouseClicked
        try {
            // TODO add your handling code here:
            Helper helper = new Helper();
            String id = helper.getValueRows(tb_stock1, 0);

            lbl_ID.setText(id);
        } catch (Exception e) {
            Logger.getLogger(Storage.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tb_stock1MouseClicked

    private void btn_refresh1jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh1jButton2ActionPerformed
        // TODO add your handling code here:
        loadTableProduct();
        loadTableSold();
    }//GEN-LAST:event_btn_refresh1jButton2ActionPerformed

    private void btn_submit1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit1jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Helper helper = new Helper();
            String id = lbl_ID.getText();
            String price = tf_sellPrice.getText();
            String amount = tf_purchaseAmount.getText();
            String purchaseDate = helper.parseDateToDatabase(dp_purchaseDate1);
            
            String total = lbl_totalPrice.getText();

            String sql = "INSERT INTO sold_items (Product_ID, Sell_Price, Sell_Amount, "
            + "Sell_Date, Total_Price, status) values (?,?,?,?,?,1)";

            Map<Integer, Object> map = new HashMap<>();
            map.put(1, id);
            map.put(2, price);
            map.put(3, amount);
            map.put(4, purchaseDate);
            map.put(5, total);

            if(!controller.preparedStatement(map, sql)){
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan Data");
            }
            else{
                clearForm1();
                loadTableProduct();
                loadTableSold();
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_submit1jButton1ActionPerformed

    private void btn_searchName1jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchName1jButton2ActionPerformed
        // TODO add your handling code here:
        String search = tf_search1.getText();
        String sql = "SELECT ID, Name, Type, Supplier, Amount, Price, Expired,"
                + " Purchase_Date FROM product WHERE Name LIKE '"+ search +"%' AND status != 0;";
        controller.get(tb_stock1, sql);
    }//GEN-LAST:event_btn_searchName1jButton2ActionPerformed

    private void btn_searchID1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchID1jButton1ActionPerformed
        // TODO add your handling code here:
        String search = tf_search1.getText();
        String sql = "SELECT ID, Name, Type, Supplier, Amount, Price, Expired,"
                + " Purchase_Date FROM product WHERE ID = ? AND status != 0";
        Map<Integer, Object> map = new HashMap<>();
        map.put(1, search);

        controller.getWithParameter(tb_stock1, map, sql);
    }//GEN-LAST:event_btn_searchID1jButton1ActionPerformed
   
    private void cb_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_typeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_typeMouseClicked

    private void tb_soldItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_soldItemsMouseClicked
    // TODO add your handling code here:
        btn_delete1.setEnabled(true);
        btn_submit1.setEnabled(false);
    }//GEN-LAST:event_tb_soldItemsMouseClicked

    private void btn_searchID2jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchID2jButton1ActionPerformed
        // TODO add your handling code here:
        String search = tf_search2.getText();
        String sql = "SELECT Product_ID, Sell_ID, Sell_Price, Sell_Amount, "
                + "Sell_Date, Total_Price FROM sold_items "
                + "WHERE ID = ? AND status != 0";
        Map<Integer, Object> map = new HashMap<>();
        map.put(1, search);

        controller.getWithParameter(tb_soldItems, map, sql);
    }//GEN-LAST:event_btn_searchID2jButton1ActionPerformed

    private void btn_refresh2jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh2jButton2ActionPerformed
        // TODO add your handling code here:
        loadTableProduct();
        loadTableSold();
    }//GEN-LAST:event_btn_refresh2jButton2ActionPerformed

    private void jTabbedPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane3MouseClicked
        // TODO add your handling code here:
        loadTableProduct();
        loadTableSold();
        btn_submit1.setEnabled(true);
        btn_delete1.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane3MouseClicked

    private void dp_purchaseDate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dp_purchaseDate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dp_purchaseDate1MouseClicked

    private void dp_purchaseDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_purchaseDate1ActionPerformed
        // TODO add your handling code here:
        Helper helper = new Helper();
            int many = Integer.parseInt(tf_purchaseAmount.getText());
            int much = Integer.parseInt(tf_sellPrice.getText());
        
            helper.setAngka_pertama(many);
            helper.setAngka_kedua(much);
            helper.kali(helper.getAngka_pertama(), helper.getAngka_kedua());
        
            lbl_totalPrice.setText(helper.getHasil());
    }//GEN-LAST:event_dp_purchaseDate1ActionPerformed

    private void btn_delete1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1jButton1ActionPerformed
        try{
            // TODO add your handling code here:

            String sql = "Delete FROM sold_items WHERE Sell_ID = ?";

            Helper helper = new Helper();
            String id = helper.getValueRows(tb_soldItems, 1);
            this.product_id = id;
            
            Map<Integer, Object> map = new HashMap<>();
            map.put(1, this.product_id);

            if(controller.preparedStatement(map, sql)){
                clearForm1();
                loadTableSold();
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
                btn_submit.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_delete1jButton1ActionPerformed
     
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Storage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Storage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Storage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Storage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Storage().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_refresh1;
    private javax.swing.JButton btn_refresh2;
    private javax.swing.JButton btn_searchID;
    private javax.swing.JButton btn_searchID1;
    private javax.swing.JButton btn_searchID2;
    private javax.swing.JButton btn_searchName;
    private javax.swing.JButton btn_searchName1;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_submit1;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cb_supplier;
    private javax.swing.JComboBox cb_type;
    private org.jdesktop.swingx.JXDatePicker dp_expired;
    private org.jdesktop.swingx.JXDatePicker dp_purchaseDate;
    private org.jdesktop.swingx.JXDatePicker dp_purchaseDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_totalPrice;
    private javax.swing.JTable tb_soldItems;
    private javax.swing.JTable tb_stock;
    private javax.swing.JTable tb_stock1;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_purchaseAmount;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_search1;
    private javax.swing.JTextField tf_search2;
    private javax.swing.JTextField tf_sellPrice;
    // End of variables declaration//GEN-END:variables
}
